/* Auto-generated by Guing — do not edit manually */

export const designTokens = {
  colors: {
    /** #0E92CB */
    : "#0E92CB",
    /** #000000 */
    divider: "#000000",
    /** #F6F6F9 */
    dialogSectionsMasterTable: "#F6F6F9",
    /** #091C2A */
    dialogSectionsNewButtons: "#091C2A",
    /** #F5F5F5 */
    buttonsInput: "#F5F5F5",
    /** #1B293A */
    buttonsTextField: "#1B293A",
    /** #D7E3EC */
    icons1: "#D7E3EC",
    /** #7C88A6 */
    iconsTableCell: "#7C88A6",
    /** #295365 */
    text: "#295365",
    /** #505D6F */
    disabled: "#505D6F",
    /** #6C7683 */
    disabledText: "#6C7683",
    /** #7A7A7A */
    dividerStroke: "#7A7A7A",
    /** #F05656 */
    error: "#F05656",
    /** #25A96B */
    greenSuccess: "#25A96B",
    /** #8E8EA9 */
    headerIcons: "#8E8EA9",
    /** #2F3545 */
    hover: "#2F3545",
    /** #BA7714 */
    orangeWarning: "#BA7714",
    /** #2196F3 */
    primaryButtons: "#2196F3",
    /** #0C98B0 */
    primaryTextField: "#0C98B0",
    /** #8B4ED6 */
    purple: "#8B4ED6",
    /** #C84747 */
    redError: "#C84747",
    /** #232D42 */
    section: "#232D42",
    /** #E7F4FD */
    select: "#E7F4FD",
    /** #223B4E */
    selected: "#223B4E",
    /** #2F3649 */
    textField: "#2F3649",
    /** #FFFFFF */
    white: "#FFFFFF",
    /** #ACBFCB */
    textFieldHeader: "#ACBFCB",
    /** #1A99CD */
    blueInfo: "#1A99CD",
  },
  typography: {
    interSmiBold: {
      fontFamily: "Inter",
      fontSize: 14,
      fontWeight: 700,
      lineHeight: "normal",
    },
    interRegular: {
      fontFamily: "Inter",
      fontSize: 14,
      fontWeight: 400,
      lineHeight: "normal",
    },
    interMedium: {
      fontFamily: "Inter",
      fontSize: 14,
      fontWeight: 500,
      lineHeight: "normal",
    },
    primaryButtons: {
      fontFamily: "Inter",
      fontSize: 64,
      fontWeight: 600,
      lineHeight: "normal",
    },
    primary2: {
      fontFamily: "Inter",
      fontSize: 64,
      fontWeight: 600,
      lineHeight: "normal",
      textTransform: "uppercase",
    },
    seconderyText: {
      fontFamily: "Inter",
      fontSize: 20,
      fontWeight: 500,
      lineHeight: 1.25,
    },
    textBody: {
      fontFamily: "Inter",
      fontSize: 18,
      fontWeight: 500,
      lineHeight: "normal",
    },
    largeHeader: {
      fontFamily: "Inter",
      fontSize: 20,
      fontWeight: 600,
      lineHeight: 1.25,
    },
    subheader: {
      fontFamily: "Inter",
      fontSize: 17,
      fontWeight: 600,
      lineHeight: 1.25,
    },
    headerSection: {
      fontFamily: "Inter",
      fontSize: 17,
      fontWeight: 600,
      lineHeight: 1.25,
      letterSpacing: 0.5,
    },
    headerTextField: {
      fontFamily: "Inter",
      fontSize: 32,
      fontWeight: 600,
      lineHeight: 1.25,
    },
    headerTextField2: {
      fontFamily: "Inter",
      fontSize: 32,
      fontWeight: 600,
      lineHeight: 1.25,
      textTransform: "uppercase",
    },
    headerTextField3: {
      fontFamily: "Inter",
      fontSize: 24,
      fontWeight: 600,
      lineHeight: 1.25,
    },
    tableHeader: {
      fontFamily: "Inter",
      fontSize: 14,
      fontWeight: 600,
      lineHeight: 1.25,
    },
    bodyBold: {
      fontFamily: "Inter",
      fontSize: 14,
      fontWeight: 500,
      lineHeight: 1.25,
    },
    body: {
      fontFamily: "Inter",
      fontSize: 14,
      fontWeight: 400,
      lineHeight: 1.25,
    },
    inter14MedButton: {
      fontFamily: "Inter",
      fontSize: 14,
      fontWeight: 500,
      lineHeight: 1.25,
      letterSpacing: 1,
    },
    boldSmallText: {
      fontFamily: "Inter",
      fontSize: 12,
      fontWeight: 600,
      lineHeight: 1.25,
    },
    inter12Regular: {
      fontFamily: "Inter",
      fontSize: 12,
      fontWeight: 400,
      lineHeight: 1.25,
    },
    hebrew: {
      fontFamily: "Open Sans",
      fontSize: 12,
      fontWeight: 400,
      lineHeight: 0.9,
      letterSpacing: 0.5,
    },
    textDefault: {
      fontFamily: "Inter",
      fontSize: 64,
      fontWeight: 600,
      lineHeight: 1.25,
    },
    error: {
      fontFamily: "Inter",
      fontSize: 10,
      fontWeight: 500,
      lineHeight: 1.25,
    },
    inter17Regular: {
      fontFamily: "Inter",
      fontSize: 17,
      fontWeight: 400,
      lineHeight: 1.25,
    },
    subtitle2: {
      fontFamily: "Roboto",
      fontSize: 14,
      fontWeight: 500,
      lineHeight: 1.57,
      letterSpacing: 0.1,
    },
  },
  radius: {
    tableCell: { topLeft: 5, topRight: 5, bottomRight: 5, bottomLeft: 5 },
    : { topLeft: 4, topRight: 4, bottomRight: 4, bottomLeft: 4 },
    icons: { topLeft: 11, topRight: 11, bottomRight: 11, bottomLeft: 11 },
    search: { topLeft: 2, topRight: 2, bottomRight: 2, bottomLeft: 2 },
    frame627217: { topLeft: 20, topRight: 0, bottomRight: 0, bottomLeft: 20 },
    menu: { topLeft: 0, topRight: 0, bottomRight: 4, bottomLeft: 4 },
    primarySlider: { topLeft: 100, topRight: 100, bottomRight: 100, bottomLeft: 100 },
    primarySliderThumb: { topLeft: 20, topRight: 20, bottomRight: 20, bottomLeft: 20 },
    textField: { topLeft: 4, topRight: 4, bottomRight: 0, bottomLeft: 0 },
    buttons: { topLeft: 0, topRight: 4, bottomRight: 4, bottomLeft: 0 },
    whiteNewButtons: { topLeft: 6, topRight: 6, bottomRight: 6, bottomLeft: 6 },
    whiteTableSettingsDefaultDefault1stPage: { topLeft: 0, topRight: 0, bottomRight: 3.708608865737915, bottomLeft: 3.708608865737915 },
    dialogSectionsMasterTable: { topLeft: 0, topRight: 0, bottomRight: 5, bottomLeft: 5 },
    dialogSectionsMasterTable2: { topLeft: 0, topRight: 5, bottomRight: 0, bottomLeft: 0 },
    matInputSelectionControls: { topLeft: 32, topRight: 32, bottomRight: 32, bottomLeft: 32 },
    frame627157: { topLeft: 3.708608865737915, topRight: 3.708608865737915, bottomRight: 0, bottomLeft: 0 },
    frame627159: { topLeft: 0, topRight: 0, bottomRight: 3.6848485469818115, bottomLeft: 3.6848485469818115 },
    divider: { topLeft: 50, topRight: 50, bottomRight: 50, bottomLeft: 50 },
  },
  shadows: {
    masterTable: [{"type":"drop","color":"#101828","opacity":0.05,"offsetX":0,"offsetY":1,"blur":2,"spread":0}],
    image11: [{"type":"drop","color":"#000000","opacity":0.1,"offsetX":-3,"offsetY":5,"blur":4,"spread":3}],
    backgroundPageDialog: [{"type":"drop","color":"#000000","opacity":0.25,"offsetX":0,"offsetY":4,"blur":4,"spread":0}],
    shadowLightSystem: [{"type":"drop","color":"#000000","opacity":0.22,"offsetX":0,"offsetY":1,"blur":1,"spread":0}],
  },
  borders: {
    buttonsNewButtons: { color: "#0C98B0", weight: 1, strokeAlign: "INSIDE" },
    buttonsPagination: { color: "#7A7A7A", weight: 1, strokeAlign: "INSIDE" },
    buttonsButtons: { color: "#0C98B0", weight: 1, strokeAlign: "INSIDE" },
    masterTableMasterTable: { color: "#000000", weight: 1, strokeAlign: "OUTSIDE" },
    masterTableTableForFigmaWork: { color: "#7A7A7A", weight: 1, strokeAlign: "OUTSIDE" },
    tableCell: { color: "#8B4ED6", weight: 1, strokeAlign: "INSIDE" },
    inputStateDefaultAssistiveTextFalse: { color: "#295365", weight: 1, strokeAlign: "INSIDE" },
    inputStateDisabledAssistiveTextFalse: { color: "#505D6F", weight: 1, strokeAlign: "INSIDE" },
    inputStateErrorAssistiveTextFalse: { color: "#F05656", weight: 1, strokeAlign: "INSIDE" },
    matCard: { color: "#0E92CB", weight: 1, strokeAlign: "INSIDE" },
    masterTable: { color: "#0E92CB", weight: 3, strokeAlign: "CENTER" },
    textField: { color: "#C84747", weight: 1, strokeAlign: "INSIDE" },
    disabled: { color: "#505D6F", weight: 0.02083333395421505, strokeAlign: "INSIDE" },
    whiteNewButtons: { color: "#000000", weight: 1, strokeAlign: "INSIDE" },
    whiteTableSettingsDefaultDefault1stPage: { color: "#295365", weight: 0.7155872583389282, strokeAlign: "INSIDE" },
    icons: { color: "#D7E3EC", weight: 0.30000001192092896, strokeAlign: "OUTSIDE" },
    frame627149: { color: "#0E92CB", weight: 1, strokeAlign: "INSIDE" },
    line04: { color: "#7A7A7A", weight: 1, strokeAlign: "CENTER" },
    divider: { color: "#000000", weight: 1, strokeAlign: "CENTER" },
    backgroundPageDialogCheckbox: { color: "#000000", weight: 1.5, strokeAlign: "INSIDE" },
    backgroundPageDialogTableSettingsCompactZebra1stPage: { color: "#000000", weight: 0.7155872583389282, strokeAlign: "INSIDE" },
    select: { color: "#0E92CB", weight: 1.5, strokeAlign: "INSIDE" },
  },
  opacity: {
    white: 1,
    masterTable: 1,
    sorting: 1,
    tableCell: 1,
    primarySlider: 0.38,
    primarySliderThumb: 0.16,
    backgroundPaperElevation0: 0.8,
    bodyText: 0.6,
    icons: 1,
  },
  gradients: {
    buttons: {"type":"linear","stops":[{"position":0,"color":"#005DB1","opacity":1},{"position":0.806,"color":"#00AAC6","opacity":1}]},
  },
} as const;

export type DesignTokens = typeof designTokens;
export type ColorKey = keyof typeof designTokens.colors;
export type TypographyKey = keyof typeof designTokens.typography;
