/* Auto-generated by Guing — do not edit manually */

export interface ColorToken {
  name: string;
  value: string;
  rgb: { r: number; g: number; b: number };
  category?: string;
}

export interface TypographyToken {
  name: string;
  fontFamily: string;
  fontSize: number;
  fontWeight: number;
  lineHeight: number | string;
  letterSpacing?: number;
  textTransform?: string;
}

export interface DesignTokens {
  colors: ColorToken[];
  typography: TypographyToken[];
}
